siteConfig:
  title: Welcome to my portfolio

permalinks:
  post: /posts/:slug
  page: /:slug

plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-prismjs
  - resolve: saber-plugin-google-analytics
    options:
      trackId: UA-134948154-1
